Create homepage
duyenttt-vbee/english-website-frontend pull request #1
Opened 2023-06-02 10:26 UTC by trinhquan1004

![image](https://github.com/duyenttt-vbee/english-website-frontend/assets/103890377/d94e6cd1-585b-43de-88fa-5d695c5fc036)

2023-06-03 02:41 UTC, duyenttt-vbee requested changes

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/pages/Home.jsx
> +/* eslint-disable react/function-component-definition */
bỏ các dòng eslint-disable

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/App.jsx
> +/* eslint-disable react/function-component-definition */
bỏ eslint-disable

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +/* eslint-disable jsx-a11y/anchor-is-valid */
bỏ các dòng eslint-disable, khi bị lỗi eslint cần sửa lại theo đúng format, trong trường hợp format đã đúng rồi thì sửa lại file `eslintrc.js` để eslint không báo các lỗi này nữa

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +    <ThemeProvider theme={defaultTheme}>
`ThemeProvider` sẽ dùng chung cho toàn bộ ứng dụng -> chuyển sang bao component `<App />`

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +    console.log({
xóa console log

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +          }}
Không nên ghi hết style vào thuộc tính `sx`, tham khảo cách sử dụng `styled-components`

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +          }}
Không nên ghi hết style vào thuộc tính `sx`, tham khảo cách sử dụng `styled-components`

2023-06-03 02:41 UTC, duyenttt-vbee commented on src/containers/Home/index.jsx
> +          }}
Tương tự với các component còn lại

2023-06-03 11:47 UTC, haitd-vbee requested changes
- Đưa Copyright vào 1 component riêng
- Chuyển đường dẫn url(https://source.unsplash.com/random?wallpapers thành 1 hằng số
- Style đủ ngắn thì chuyển thành 1 dòng, hàm đủ ngắn thì chuyển thành inline sẽ dễ đọc hơn
- Xóa các dấu tab thừa ở index.style.js

2023-06-03 11:47 UTC, haitd-vbee commented on src/containers/Home/index.style.js
> +  backgroundColor: (t) =>
Sao chỗ này tab thừa nhiều thế em

2023-06-03 11:47 UTC, haitd-vbee commented on src/containers/Home/index.jsx
> +const Copyright = (props) => (
Vì component này có thể sẽ dùng ở nhiều page khác nhau nên để tránh việc mỗi 1 page em lại định nghĩa 1 Copyright thì em tạo thêm một folder components để chứa các component mà có thể tái sử dụng rồi chuyển component này vào nhé

2023-06-03 11:47 UTC, haitd-vbee commented on src/containers/Home/index.jsx
> +          backgroundImage: 'url(https://source.unsplash.com/random?wallpapers',
'url(https://source.unsplash.com/random?wallpapers' Đưa đường dẫn này vào 1 hằng số

2023-06-03 11:47 UTC, haitd-vbee commented on src/containers/Home/index.jsx
> +          sx={{
Style ngắn thì chuyển thành 1 dòng thôi em

2023-06-04 13:18 UTC, duyenttt-vbee approved these changes

2023-06-04 13:18 UTC, merged